server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9091}
  topic:
    test: test
  consumer:
    group-id: orchestrator-group
    auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF